name: pokemon_deck_builder
description: Pokemon deck building app.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.16.0'
  flutter: '>=2.10.3'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter:
  cupertino_icons: 1.0.2
  flutter_bloc:
  json_annotation:
  freezed_annotation:
  analyzer:
  intl: 0.17.0
  responsive_framework: 0.1.5
  bloc_concurrency:
  dio:
  flutter_localizations:
    sdk: flutter
  flutter_form_builder: 7.0.0
  form_builder_validators: 7.2.0
  sqflite: 2.0.2
  path_provider:
  l: 3.1.0
  http: 0.13.4
  syncfusion_flutter_charts: 19.4.56

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable:
  freezed:
  build_runner:
  dart_code_metrics:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_intl:
  enabled: true
